name: Gemini Config
version: 1.0.0
models:
  - name: Gemini 2.5 Flash
    provider: gemini
    model: gemini-2.5-flash
    apiKey: AIzaSyBC_85yZArQn79lpxPYM4a60bkrepFTuf0
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      contextLength: 1048576
      maxTokens: 8192
    capabilities:
      - tool_use
      - image_input
